### ISSUE TITLE
Fails with BiocCheck in release

### ISSUE THREAD

**Issue by alanocallaghan** [insightsengineering/bioc-check-action#10]
Interface for `BiocCheck()` has changed from `BiocCheck <- function(package=".", ...)`: https://github.com/Bioconductor/BiocCheck/blob/31109f831a7bcfd30ebd5c3a145ffdea0f348c1f/R/BiocCheck.R#L77

to: `BiocCheck <- function(package=".", checkDir = dirname(package), debug = FALSE, ...)`: https://github.com/Bioconductor/BiocCheck/blob/0248376d40e7ebd5f5b861b056154cd6f335f87c/R/BiocCheck.R#L102-L103

This means you end up with (presumably among other weird errors) `─ BiocCheckDir: c("FALSE/BASiCStan.BiocCheck", "TRUE/BASiCStan.BiocCheck")` which means you get an error later as `Error in if (!dir.exists(bioccheck_dir)) dir.create(bioccheck_dir, recursive = TRUE) :   the condition has length > 1`

**Comment by cicdguy** [comment]
Thanks for the report, @Alanocallaghan. Will fix this accordingly.
